# Generated by Django 4.1.1 on 2023-02-21 14:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("corecode", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="image",
        ),
        migrations.AlterField(
            model_name="academic",
            name="image",
            field=models.ImageField(blank=True, upload_to="front/images/"),
        ),
        migrations.AlterField(
            model_name="admission",
            name="image",
            field=models.ImageField(blank=True, upload_to="front/images/"),
        ),
        migrations.AlterField(
            model_name="club",
            name="image",
            field=models.ImageField(blank=True, upload_to="front/club/"),
        ),
        migrations.AlterField(
            model_name="founder",
            name="image",
            field=models.ImageField(blank=True, upload_to="front/images/"),
        ),
        migrations.AlterField(
            model_name="hostel",
            name="image",
            field=models.ImageField(blank=True, upload_to="front/images/"),
        ),
        migrations.AlterField(
            model_name="mission",
            name="image",
            field=models.ImageField(blank=True, upload_to="front/images/"),
        ),
        migrations.AlterField(
            model_name="school",
            name="image",
            field=models.ImageField(blank=True, upload_to="front/images/"),
        ),
        migrations.AlterField(
            model_name="staff_front",
            name="image",
            field=models.ImageField(blank=True, upload_to="front/images/"),
        ),
        migrations.AlterField(
            model_name="vision",
            name="image",
            field=models.ImageField(blank=True, upload_to="front/images/"),
        ),
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("content", models.TextField()),
                ("images", models.FileField(upload_to="")),
                ("date", models.DateField()),
                (
                    "host",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
