# Generated by Django 4.1.1 on 2023-02-23 10:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("corecode", "0002_remove_event_image_alter_academic_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="club",
            name="founder_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="event",
            name="date",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="time_from",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="time_to",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="public_message",
            name="date",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="staff_message",
            name="date",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="student_message",
            name="date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
