# Generated by Django 4.1.1 on 2023-02-23 10:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("corecode", "0003_alter_club_founder_date_alter_event_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="event",
            name="time_from",
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="event",
            name="time_to",
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
