# Generated by Django 4.1.1 on 2023-02-23 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("corecode", "0004_alter_event_date_alter_event_time_from_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="academic",
            old_name="image",
            new_name="img",
        ),
        migrations.RenameField(
            model_name="admission",
            old_name="image",
            new_name="img",
        ),
        migrations.RenameField(
            model_name="club",
            old_name="image",
            new_name="img",
        ),
        migrations.RenameField(
            model_name="founder",
            old_name="image",
            new_name="img",
        ),
        migrations.RenameField(
            model_name="hostel",
            old_name="image",
            new_name="img",
        ),
        migrations.RenameField(
            model_name="mission",
            old_name="image",
            new_name="img",
        ),
        migrations.RenameField(
            model_name="news",
            old_name="images",
            new_name="imgs",
        ),
        migrations.RenameField(
            model_name="school",
            old_name="image",
            new_name="img",
        ),
        migrations.RenameField(
            model_name="staff_front",
            old_name="image",
            new_name="img",
        ),
        migrations.RenameField(
            model_name="vision",
            old_name="image",
            new_name="img",
        ),
    ]
