# Generated by Django 4.1.1 on 2023-02-23 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "corecode",
            "0005_rename_image_academic_img_rename_image_admission_img_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="news",
            old_name="imgs",
            new_name="images",
        ),
        migrations.RemoveField(
            model_name="academic",
            name="img",
        ),
        migrations.RemoveField(
            model_name="admission",
            name="img",
        ),
        migrations.RemoveField(
            model_name="club",
            name="img",
        ),
        migrations.RemoveField(
            model_name="founder",
            name="img",
        ),
        migrations.RemoveField(
            model_name="hostel",
            name="img",
        ),
        migrations.RemoveField(
            model_name="mission",
            name="img",
        ),
        migrations.RemoveField(
            model_name="school",
            name="img",
        ),
        migrations.RemoveField(
            model_name="staff_front",
            name="img",
        ),
        migrations.RemoveField(
            model_name="vision",
            name="img",
        ),
        migrations.AddField(
            model_name="academic",
            name="image",
            field=models.ImageField(blank=True, upload_to="images"),
        ),
        migrations.AddField(
            model_name="admission",
            name="image",
            field=models.ImageField(blank=True, upload_to="images"),
        ),
        migrations.AddField(
            model_name="club",
            name="image",
            field=models.ImageField(blank=True, upload_to="club"),
        ),
        migrations.AddField(
            model_name="founder",
            name="image",
            field=models.ImageField(blank=True, upload_to="images"),
        ),
        migrations.AddField(
            model_name="hostel",
            name="image",
            field=models.ImageField(blank=True, upload_to="images"),
        ),
        migrations.AddField(
            model_name="mission",
            name="image",
            field=models.ImageField(blank=True, upload_to="images"),
        ),
        migrations.AddField(
            model_name="school",
            name="image",
            field=models.ImageField(blank=True, upload_to="images"),
        ),
        migrations.AddField(
            model_name="staff_front",
            name="image",
            field=models.ImageField(blank=True, upload_to="images"),
        ),
        migrations.AddField(
            model_name="vision",
            name="image",
            field=models.ImageField(blank=True, upload_to="images"),
        ),
    ]
