# Generated by Django 4.1.1 on 2023-02-23 14:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("corecode", "0006_rename_imgs_news_images_remove_academic_img_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="image",
            field=models.ImageField(blank=True, upload_to="images"),
        ),
        migrations.AddField(
            model_name="event",
            name="posted_date",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2023, 2, 23, 14, 35, 27, 35215, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="article",
            name="date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
