# Generated by Django 4.1.1 on 2023-03-02 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("staffs", "0001_initial"),
        ("corecode", "0007_article_image_event_posted_date_alter_article_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssignSubject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "class_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="corecode.studentclass",
                    ),
                ),
                (
                    "teacher_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="staffs.staff"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SubjectItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject_name", models.CharField(max_length=30)),
                (
                    "subject_data",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="corecode.assignsubject",
                    ),
                ),
            ],
        ),
    ]
