# Generated by Django 4.1.1 on 2023-03-26 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("staffs", "0001_initial"),
        ("corecode", "0008_assignsubject_subjectitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignsubject",
            name="class_name",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="corecode.studentclass",
            ),
        ),
        migrations.AlterField(
            model_name="assignsubject",
            name="teacher_name",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="staffs.staff"
            ),
        ),
        migrations.AlterField(
            model_name="subjectitem",
            name="subject_data",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="corecode.assignsubject",
            ),
        ),
    ]
