# Generated by Django 4.1.1 on 2023-03-28 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("corecode", "0010_alter_assignsubject_class_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subjectitem",
            name="subject_name",
            field=models.CharField(max_length=30),
        ),
    ]
