# Generated by Django 4.1.1 on 2023-03-28 21:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("corecode", "0012_alter_subjectitem_subject_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subjectitem",
            name="subject_name",
            field=models.CharField(
                default=datetime.datetime(
                    2023, 3, 28, 21, 24, 11, 356951, tzinfo=datetime.timezone.utc
                ),
                max_length=30,
            ),
            preserve_default=False,
        ),
    ]
